spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/novaBaza
    username: postgres
    password: baza123
server:
  port: 8084
  error:
    include-message: always

