spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    admin: communication-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ## populate from secret
    username: ## populate from secret
    password: ## populate from secret
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: slanjeobavijesti@gmail.com
    password: ## populate from secret
    protocol: smtp
    test-connection: false
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
server:
  port: 8084
  error:
    include-message: always
