server:
  tomcat:
    threads:
      max: 100
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dsekulic1/config-repo-elmir.git
          username: dsekulic1@etf.unsa.ba
          password: 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
          skip-ssl-validation: true
          ignore-local-ssh-settings: true
          clone-on-start: true
          default-label: main
  security:
    user:
      name: root
      password: root