server:
  tomcat:
    threads:
      max: 100
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tjapalak1/config-repo.git
          username: tjapalak1@etf.unsa.ba
          password: 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
          skip-ssl-validation: true
          ignore-local-ssh-settings: true
          clone-on-start: true
          default-label: main
  security:
    user:
      name: root
      password: root